name: simple-streamlit
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - python-dotenv
    - matplotlib
    - streamlit
    - scikit-learn
    - boto3
    - ipykernel
    - vaderSentiment
    - plotly=5.19.0